// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB54NiYLcZhHSTGQZRBiWQUrzGznTfaOc0',
    appId: '1:241758124993:web:043a0eea6b434772f88d40',
    messagingSenderId: '241758124993',
    projectId: 'via-libre-38d87',
    authDomain: 'via-libre-38d87.firebaseapp.com',
    databaseURL: 'https://via-libre-38d87-default-rtdb.firebaseio.com',
    storageBucket: 'via-libre-38d87.firebasestorage.app',
    measurementId: 'G-2H88C016RN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHa3QSJrQKuXVljDoIn6ggQvkXjqPHzIU',
    appId: '1:241758124993:android:6666af2f379234bcf88d40',
    messagingSenderId: '241758124993',
    projectId: 'via-libre-38d87',
    databaseURL: 'https://via-libre-38d87-default-rtdb.firebaseio.com',
    storageBucket: 'via-libre-38d87.firebasestorage.app',
  );
}
